backend:
  namespace: backend-uat
  image: ghcr.io/BankMarkBenz/backend
  tag: uat
  replicas: 1
  imagePullSecrets: registry
  port: 8080
  healthCheckPath: "/health"
ingress:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$2
  host: bankandmark.codes
  path: "/backend(/|$)(.*)"
  serviceType: ClusterIP
extraEnv:
  COMMIT_SHA: CHANGEME