name: dev-env
on:
  push:
    branches:
      - dev
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
#      - name: build code
#        uses: LucaFeger/action-maven-cli@1.1.0
#        with:
#          args: "clean install"
#      - run: ls -l
#      - name: SonarQube Scan
#        uses: kitabisa/sonarqube-action@v1.1.0
#        with:
#          host: ${{ secrets.SONARQUBE_HOST }}
#          login: ${{ secrets.SONARQUBE_TOKEN }}
#          projectKey: "BackEndService"
#          projectName: "BackEndService"
#          projectVersion: "v1.0.0"
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ghcr.io/bankmarkbenz/backend:dev
  deploy:
    needs: build
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: get-credentials
        uses: google-github-actions/get-gke-credentials@main
        with:
          cluster_name: bankmarkbenz-cluster
          location: asia-east1-a
          credentials: ${{ secrets.GKE_CREDENTIALS }}
      - name: deploy
        uses: 'deliverybot/helm@v1'
        with:
          helm: helm3
          release: backend-dev-service
          namespace: backend-dev
          chart: k8s/helm
          value-files: k8s/helm-values/values-backend-dev.yaml
          values: |
            {
              "extraEnv": {
                "COMMIT_SHA": "${{ github.sha }}"
              }
            }